services:
  # Discord bot service
  discord-bot:
    build: .
    container_name: discord_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "yarn prisma migrate deploy && \
        yarn scrape && \
        yarn prisma db seed && \
        yarn start"
    networks:
      - gunpla-wishlist-bot

  # PostgreSQL database service
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gunpla-wishlist-bot

volumes:
  postgres_data:
networks:
  gunpla-wishlist-bot:
    name: gunpla-wishlist-bot
    driver: bridge
